# permissions for end users to view argocds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-viewer-role
rules:
- apiGroups:
  - addons.configdelivery.anthos.io
  resources:
  - argocds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - addons.configdelivery.anthos.io
  resources:
  - argocds/status
  verbs:
  - get
