# permissions for end users to edit configsyncs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: configsync-editor-role
rules:
- apiGroups:
  - addons.configdelivery.anthos.io
  resources:
  - configsyncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - addons.configdelivery.anthos.io
  resources:
  - configsyncs/status
  verbs:
  - get
