# permissions for end users to edit managedargocds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: managedargocd-editor-role
rules:
- apiGroups:
  - addons.configdelivery.anthos.io
  resources:
  - managedargocds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - addons.configdelivery.anthos.io
  resources:
  - managedargocds/status
  verbs:
  - get
