# permissions for end users to view managedargocds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: managedargocd-viewer-role
rules:
- apiGroups:
  - addons.configdelivery.anthos.io
  resources:
  - managedargocds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - addons.configdelivery.anthos.io
  resources:
  - managedargocds/status
  verbs:
  - get
